version: 1
accounts:
- name: alice
  coins:
  - 200000000seda
- name: bob
  coins:
  - 100000000seda
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 100000seda
validators:
- name: alice
  bonded: 100000000seda
