name: Lint

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    tags:
      - v*
    branches:
      - main

permissions:
  contents: read
  repository-projects: read
  packages: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  golangci:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout 10m --tests=false
