# This workflow is useful if you need to make a new release manually for testing purposes.
#
# This uploads the zip release bundle to `transfer.sh`. Where it will remain for 14 days.
# NOTE: This file can be overwritten so be cautious when downloading.
# The idea behind this process is to avoid publishing a test version to our Github Release page.
on:
  workflow_dispatch:
    inputs:
      password:
        required: true

jobs:
  check_pass:
    name: Check password
    runs-on: ubuntu-latest
    outputs:
      is_allowed: ${{ steps.check.outputs.is_allowed }}
    steps:
      - id: check
        run: |
          password=${{ secrets.CI_PASSWORD }}
          if [[ "${{ github.event.inputs.password }}" == "${password}" ]]; then
            echo "is_allowed=true" >> $GITHUB_OUTPUT
          else
            echo "is_allowed=false" >> $GITHUB_OUTPUT
          fi

  test_release:
    needs: check_pass
    if: ${{ needs.check_pass.outputs.is_allowed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install arm Arch
        run: |
          sudo apt-get update
          sudo apt-get -y install --no-install-recommends gcc-aarch64-linux-gnu libc6-dev-arm64-cross

      - name: Install Ignite
        run: |
          curl https://get.ignite.com/cli! | bash

      - name: Create Arm Node Binary
        env: 
          GOFLAGS: '-buildvcs=false'
          CGO_ENABLED: 1
          CC: 'aarch64-linux-gnu-gcc'
          CXX: 'aarch64-linux-gnu-g++'
        run: |
          ignite chain build --release -t linux:arm64 -y -v

      - name: Upload to transfer.sh
        id: upload
        run: |
          TRANSFER_URL=$(curl --upload-file release/seda-chain_linux_arm64.tar.gz https://transfer.sh/seda-chain_linux_arm64.tar.gz)
          echo "transfer_url=$TRANSFER_URL" >> $GITHUB_OUTPUT

      - name: Use transfer URL
        run: echo "The binary can be downloaded from ${{ steps.upload.outputs.transfer_url }}"
