name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, labeled]

env:
  GO_VERSION: "1.21.0"
  GOPRIVATE: github.com/sedaprotocol/vrf-go
  GITHUB_TOKEN: ${{ secrets.PAT }}

permissions:
  contents: read
  repository-projects: read
  packages: read

concurrency:
  group: ci-${{ github.ref }}-tests
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
          cache: true
          cache-dependency-path: go.sum
      - run: git config --global url.https://${GITHUB_TOKEN}@github.com/.insteadOf https://github.com/
      - name: Test & coverage report creation
        run: make test-unit-cover
      - uses: actions/upload-artifact@v3
        with:
          name: "${{ github.sha }}-${{ matrix.part }}-coverage"
          path: ./${{ matrix.part }}profile.out

  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: git config --global url.https://${GITHUB_TOKEN}@github.com/.insteadOf https://github.com/
      - name: Test e2e
        run: |
          make test-e2e

  lint:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/sedaprotocol/vrf-go
      GITHUB_TOKEN: ${{ secrets.PAT }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Buf
        uses: bufbuild/buf-setup-action@v1.26.1
      - name: Lint Proto
        run: make proto-lint
      - name: clang-format Check
        uses: jidicula/clang-format-action@v4.11.0
        with:
          clang-format-version: 17
          check: true
          diff: true
          extensions: .proto
          path: proto
          style: file